# Generated by Django 4.2.5 on 2023-09-18 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalanceAcademico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balanceAcademicoID', models.CharField(max_length=20)),
                ('program', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Becas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='InformacionFinanciera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('informeID', models.CharField(max_length=20)),
                ('dineroAsignado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('dineroUsado', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiaID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('scheduale', models.DateTimeField(null=True)),
                ('assists', models.PositiveIntegerField()),
                ('balanceAcademicoID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.balanceacademico')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoActividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguimientoActividadesID', models.CharField(max_length=20)),
                ('actividadID', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('lastName', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Materia Cancelada', 'Materia Cancelada'), ('Materia en Curso', 'Materia en Curso'), ('Materia completada', 'Materia completada')], max_length=20)),
                ('materiaID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.materia')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semesterID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('faculty', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True)),
                ('studentCode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.student')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoCREA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seguimientoCreaID', models.CharField(max_length=20)),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.user')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoBeca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reporteBecaID', models.CharField(max_length=20)),
                ('testimonio', models.CharField(max_length=100)),
                ('SeguimientoActividadesID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.seguimientoactividades')),
                ('balanceAcademicoID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.balanceacademico')),
                ('informacionFinancieraID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.informacionfinanciera')),
                ('studentCode', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.student')),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Filantropia', 'Filantropia'), ('Bienestar', 'Bienestar'), ('Contabilidad', 'Contabilidad'), ('Director de Programa', 'Director de Programa')], max_length=20)),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donanteID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('typeBecas', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.becas')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultaID', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
                ('reason', models.CharField(max_length=50)),
                ('result', models.CharField(max_length=20)),
                ('seguimientoCreaID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.seguimientocrea')),
            ],
        ),
        migrations.AddField(
            model_name='becas',
            name='studentCode',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.student'),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alertaID', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=50)),
                ('userID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.user')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actividadID', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('assists', models.PositiveIntegerField()),
                ('seguimientoActividadesID', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.seguimientoactividades')),
            ],
        ),
    ]
