# Generated by Django 4.2.5 on 2023-10-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='alertaID',
        ),
        migrations.AddField(
            model_name='alerta',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='title',
            field=models.CharField(default='Notificación', max_length=40),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='type',
            field=models.IntegerField(choices=[(0, 'Solicitud de información'), (1, 'Subida de información'), (2, 'ningun tipo')], default=2),
        ),
    ]
