# Generated by Django 4.2.5 on 2023-10-11 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balanceacademico',
            name='SeguimientoBecaID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.seguimientobeca'),
        ),
    ]
