# Generated by Django 4.2.5 on 2023-10-02 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta',
            name='alertaID',
        ),
        migrations.RemoveField(
            model_name='becas',
            name='studentCode',
        ),
        migrations.AddField(
            model_name='alerta',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='alerta',
            name='title',
            field=models.CharField(default='Notification', max_length=40),
        ),
        migrations.AddField(
            model_name='student',
            name='typeBecas',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.becas'),
        ),
        migrations.AlterField(
            model_name='alerta',
            name='type',
            field=models.IntegerField(choices=[(0, 'Solicitud de informacion'), (1, 'Subida de informacion'), (2, 'ningun tipo')], default=2),
        ),
    ]
