# Generated by Django 4.2.5 on 2023-10-03 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userID',
        ),
    ]
