# Generated by Django 4.2.5 on 2023-10-03 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0002_remove_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='type',
            field=models.IntegerField(choices=[(0, 'Solicitud de información'), (1, 'Subida de información'), (2, 'ningun tipo'), (3, 'Actualización de actividades no academicas de un estudiante')], default=2),
        ),
    ]
