# Generated by Django 4.2.5 on 2023-11-15 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0002_alter_alerta_studentid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='name',
            field=models.CharField(choices=[('Primer Semestre', 'Primer Semestre'), ('Segundo Semestre', 'Segundo Semestre'), ('Tercer Semestre', 'Tercer Semestre'), ('Cuarto Semestre', 'Cuarto Semestre'), ('Quinto Semestre', 'Quinto Semestre'), ('Sexto Semestre', 'Sexto Semestre'), ('Septimo Semestre', 'Septimo Semestre'), ('Octavo Semestre', 'Octavo Semestre'), ('Noveno Semestre', 'Noveno Semestre'), ('Decimo Semestre', 'Decimo Semestre'), ('Onceavo Semestre', 'Onceavo Semestre'), ('Doceavo Semestre', 'Doceavo Semestre')], max_length=200),
        ),
    ]
