# Generated by Django 4.2.5 on 2023-10-31 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0002_alter_student_id'),
        ('Icesi_Students_Management', '0002_historyactivityassistance'),
    ]

    operations = [
    ]
