# Generated by Django 4.2.5 on 2023-10-09 01:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0002_remove_alerta_alertaid_remove_becas_studentcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='seguimientoCreaID',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='balanceAcademicoID',
        ),
        migrations.RemoveField(
            model_name='roles',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='seguimientobeca',
            name='SeguimientoActividadesID',
        ),
        migrations.RemoveField(
            model_name='seguimientobeca',
            name='balanceAcademicoID',
        ),
        migrations.RemoveField(
            model_name='seguimientobeca',
            name='informacionFinancieraID',
        ),
        migrations.RemoveField(
            model_name='seguimientobeca',
            name='studentCode',
        ),
        migrations.RemoveField(
            model_name='seguimientobeca',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='seguimientocrea',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='semester',
            name='studentCode',
        ),
        migrations.RemoveField(
            model_name='status',
            name='materiaID',
        ),
        migrations.RemoveField(
            model_name='student',
            name='typeBecas',
        ),
        migrations.AddField(
            model_name='student',
            name='beca',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='BecaType', to='Icesi_Students_Management.becas'),
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True),
        ),
        migrations.DeleteModel(
            name='Actividad',
        ),
        migrations.DeleteModel(
            name='BalanceAcademico',
        ),
        migrations.DeleteModel(
            name='Consulta',
        ),
        migrations.DeleteModel(
            name='InformacionFinanciera',
        ),
        migrations.DeleteModel(
            name='Materia',
        ),
        migrations.DeleteModel(
            name='Roles',
        ),
        migrations.DeleteModel(
            name='SeguimientoActividades',
        ),
        migrations.DeleteModel(
            name='SeguimientoBeca',
        ),
        migrations.DeleteModel(
            name='SeguimientoCREA',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
