# Generated by Django 4.2.5 on 2023-10-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0002_remove_actividad_actividadid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informacionfinanciera',
            name='id',
        ),
        migrations.AddField(
            model_name='informacionfinanciera',
            name='extraInfo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='informacionfinanciera',
            name='financialNote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='informacionfinanciera',
            name='studentID',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='informacionfinanciera',
            name='studentName',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='informacionfinanciera',
            name='informeID',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
