# Generated by Django 4.2.5 on 2023-10-29 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0002_alter_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='StudentID',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Icesi_Students_Management.student'),
        ),
    ]
