# Generated by Django 4.2.5 on 2023-09-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0002_remove_alerta_alertaid_alerta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='title',
            field=models.CharField(default='Notificación', max_length=40),
        ),
    ]
