# Generated by Django 4.2.5 on 2023-09-28 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0003_alerta_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='actividadID',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='seguimientoActividadesID',
        ),
        migrations.AddField(
            model_name='actividad',
            name='student',
            field=models.CharField(default='A00381035', max_length=9),
        ),
    ]
