# Generated by Django 4.2.5 on 2023-10-09 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0003_remove_consulta_seguimientocreaid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='becas',
            name='alimentacion',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='becas',
            name='percentage',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='becas',
            name='transporte',
            field=models.BooleanField(default=None),
        ),
    ]
