# Generated by Django 4.2.5 on 2023-10-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0003_remove_informacionfinanciera_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionfinanciera',
            name='informeID',
            field=models.IntegerField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
    ]
