# Generated by Django 4.2.5 on 2023-10-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0003_rename_materiaid_materia_codmateria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='nota',
            field=models.FloatField(default=0.0),
        ),
    ]
