# Generated by Django 4.2.5 on 2023-11-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0003_alter_semester_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='carreraID',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
