# Generated by Django 4.2.7 on 2023-11-25 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0004_alter_carrera_carreraid'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerta',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
