# Generated by Django 4.2.5 on 2023-10-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0004_alter_informacionfinanciera_informeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacionfinanciera',
            name='informeID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False, unique=True),
        ),
    ]
