# Generated by Django 4.2.5 on 2023-10-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0004_becas_alimentacion_becas_percentage_becas_transporte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True),
        ),
    ]
