# Generated by Django 4.2.5 on 2023-09-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0004_remove_actividad_actividadid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='student',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
