# Generated by Django 4.2.5 on 2023-11-26 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0004_alter_carrera_carreraid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Oficina de Contabilidad'), (2, 'Oficina de Bienestar Universitario'), (3, 'Oficina de Balance Academico'), (4, 'Oficina de Filantropía'), (5, 'Oficina de CREA')], default=0),
        ),
    ]
