# Generated by Django 4.2.5 on 2023-10-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0005_alter_actividad_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='code',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
