# Generated by Django 4.2.7 on 2023-11-26 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0005_alerta_isread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='type',
            field=models.IntegerField(choices=[(0, 'None'), (1, 'Actualizacion de informacion contabilidad'), (2, 'Actualizacion de informacion Bienestar Universitario'), (3, 'Actualizacion de informacion Director de programa'), (4, 'Actualización de actividades no academicas de un estudiante'), (5, 'Actualización de Actividades del CREA')], default=0),
        ),
    ]
