# Generated by Django 4.2.5 on 2023-11-27 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Icesi_Students_Management', '0002_auto_20231126_2236'),
        ('Icesi_Students_Management', '0005_alter_alerta_type'),
        ('Icesi_Students_Management', '0006_alter_alerta_type'),
    ]

    operations = [
    ]
